### ISSUE TITLE
PHP version issue

### ISSUE THREAD

**Issue by smockensturm** [shankx50/constant-contact-subscribe#3]
Hey there,

What is it about this plug-in that makes it require > PHP 5.6 ?

Is it the vendor/ composer/ guzzle stuff? Isn't there a better way to do that?

**Comment by shankx50** [comment]
Hey! I had limited time when I needed this plugin, so I modeled it after https://straightupcraft.com/craft-plugins/mailchimp-subscribe. I did encounter a problem with guzzle when older PHP versions. I am sure there is a better way, but I haven't had the time to address that issue yet.

**Comment by smockensturm** [comment]
I understand. It would be helpful if you put the PHP requirement up front somewhere. :)
