### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by daltonrooney** [shankx50/constant-contact-subscribe#4]
Using your code example, I get the following error:

```
require_once(/app/craft/plugins/constantcontactsubscribe/vendor/autoload.php): failed to open stream: No such file or directory

/app/craft/plugins/constantcontactsubscribe/controllers/ConstantContactSubscribe_ListController.php(4)

require_once(CRAFT_PLUGINS_PATH.'constantcontactsubscribe/vendor/autoload.php');
```

It looks like the vendor directory has been removed but it's still being called by the ListController.

**Comment by shankx50** [comment]
Hi @daltonrooney. My customer stopped using this plugin and I currently do not have the time to look after this issue. However, I would love a pull request so we can get it fixed.

If not, then I'll do it as soon as my schedule frees up a bit.

**Comment by shankx50** [comment]
Thank you @rachelrine for taking care of this!
